# Generated by Django 4.0.4 on 2022-04-19 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('channel_id', models.IntegerField()),
                ('channel_login', models.CharField(max_length=250)),
                ('object_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
            ],
            options={
                'verbose_name_plural': 'ChannelData',
            },
        ),
        migrations.CreateModel(
            name='FetchDateTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
            ],
            options={
                'verbose_name_plural': 'FetchDateTimes',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_count', models.IntegerField()),
                ('stream_started_at', models.DateTimeField(null=True)),
                ('object_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.channeldata')),
                ('fetch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes')),
            ],
            options={
                'verbose_name_plural': 'Streams',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=250)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=250)),
                ('response_code', models.IntegerField(null=True)),
                ('object_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('fetch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes')),
            ],
            options={
                'verbose_name_plural': 'Security',
            },
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=250)),
                ('game_id', models.IntegerField()),
                ('object_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('fetch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes')),
            ],
            options={
                'verbose_name_plural': 'GameData',
            },
        ),
        migrations.AddField(
            model_name='channeldata',
            name='fetch_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes'),
        ),
        migrations.CreateModel(
            name='CeleryFetchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
                ('fetch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes')),
            ],
            options={
                'verbose_name_plural': 'CeleryFetchQueries',
            },
        ),
    ]
