# Generated by Django 4.0.2 on 2022-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_id', models.IntegerField()),
                ('streamer_login', models.CharField(max_length=100)),
                ('streamer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
