# Generated by Django 4.0.4 on 2022-04-20 16:12

from django.db import migrations, models
import django.db.models.functions.datetime
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='object_creation_date',
            field=models.DateTimeField(default=django.db.models.functions.datetime.TruncSecond(django.utils.timezone.now), verbose_name='Created'),
        ),
    ]
