# Generated by Django 4.0.4 on 2022-04-18 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryFetchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'verbose_name_plural': 'CeleryFetchQueries',
            },
        ),
        migrations.CreateModel(
            name='FetchDateTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'FetchDateTimes',
            },
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=250)),
                ('game_id', models.IntegerField()),
                ('object_creation_date', models.DateTimeField(auto_now_add=True)),
                ('fetch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes')),
            ],
            options={
                'verbose_name_plural': 'GameData',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=250)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=250)),
                ('object_creation_date', models.DateTimeField(auto_now_add=True)),
                ('fetch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes')),
            ],
            options={
                'verbose_name_plural': 'Security',
            },
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
        migrations.AddField(
            model_name='celeryfetchquery',
            name='fetch_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fetchdatetimes'),
        ),
    ]
