# Generated by Django 4.0.4 on 2022-04-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_celeryfetchquery_fetchdatetimes_gamedata_security_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchdatetimes',
            name='fetch_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='object_creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='security',
            name='object_creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
