# Generated by Django 4.0.2 on 2022-04-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamedata_streamerdata_delete_leads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamedata',
            options={'verbose_name_plural': 'Game Data'},
        ),
        migrations.AlterModelOptions(
            name='streamerdata',
            options={'verbose_name_plural': 'Streamer Data'},
        ),
    ]
