# Generated by Django 4.0.4 on 2022-04-20 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stream_object_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='object_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
