# Generated by Django 4.0.4 on 2022-04-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stream_object_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeldata',
            old_name='object_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='gamedata',
            old_name='object_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='object_creation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='object_creation_date',
            new_name='creation_date',
        ),
    ]
