# Generated by Django 4.0.4 on 2022-04-19 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fetchdatetimes_fetch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchdatetimes',
            name='fetch_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
