# Generated by Django 4.0.4 on 2022-04-19 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fetchdatetimes_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='object_creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created'),
        ),
    ]
