# Generated by Django 4.0.4 on 2022-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_object_creation_date_channeldata_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('viewers', models.IntegerField()),
                ('channel_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daily Data',
            },
        ),
        migrations.CreateModel(
            name='FifteenMinuteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('viewers', models.IntegerField()),
                ('channel_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Fifteen Minute Data',
            },
        ),
        migrations.CreateModel(
            name='FourHourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('viewers', models.IntegerField()),
                ('channel_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '4 Hour Data',
            },
        ),
        migrations.CreateModel(
            name='OneHourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('viewers', models.IntegerField()),
                ('channel_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hourly Data',
            },
        ),
        migrations.CreateModel(
            name='OneMinuteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('viewers', models.IntegerField()),
                ('channel_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'One Minute Data',
            },
        ),
    ]
