# Generated by Django 4.0.4 on 2022-04-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dailydata_fifteenminutedata_fourhourdata_onehourdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_started_at',
            new_name='stream_date',
        ),
    ]
