# Generated by Django 4.0.4 on 2022-04-19 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_security_object_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchdatetimes',
            name='fetch_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created'),
        ),
    ]
