# Generated by Django 4.0.4 on 2022-04-19 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fetchdatetimes_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchdatetimes',
            name='fetch_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 3, 36, 5, 621549, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='object_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 3, 36, 5, 622510, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='security',
            name='object_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 3, 36, 5, 621895, tzinfo=utc), verbose_name='Created'),
        ),
    ]
