# Generated by Django 4.0.4 on 2022-04-19 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fetchdatetimes_fetch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchdatetimes',
            name='fetch_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='object_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='security',
            name='object_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
