# Generated by Django 4.0.4 on 2022-04-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_fetchdatetimes_fetch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='response_code',
            field=models.IntegerField(null=True),
        ),
    ]
