# Generated by Django 4.0.4 on 2022-04-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dailydata_fifteenminutedata_fourhourdata_onehourdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyData',
        ),
        migrations.DeleteModel(
            name='FifteenMinuteData',
        ),
        migrations.DeleteModel(
            name='FourHourData',
        ),
        migrations.DeleteModel(
            name='OneHourData',
        ),
        migrations.DeleteModel(
            name='OneMinuteData',
        ),
    ]
