# Generated by Django 3.2.13 on 2022-04-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_oneminutedata_threeminutedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threeminutedata',
            options={'verbose_name_plural': 'Three Minute Data'},
        ),
    ]
