# Generated by Django 3.2.13 on 2022-05-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_timekeeping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeKeeping',
        ),
    ]
