# Generated by Django 3.2.13 on 2022-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_timekeeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_min', models.DateTimeField()),
                ('fifteen_min', models.DateTimeField()),
                ('one_hour', models.DateTimeField()),
                ('four_hour', models.DateTimeField()),
                ('daily', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Time Data',
            },
        ),
    ]
